// ignore_for_file: constant_identifier_names

abstract final class SettingBoxKey {
  static const String btmProgressBehavior = 'btmProgressBehavior',
      defaultVideoQa = 'defaultVideoQa',
      defaultVideoQaCellular = 'defaultVideoQaCellular',
      defaultAudioQa = 'defaultAudioQa',
      defaultAudioQaCellular = 'defaultAudioQaCellular',
      autoPlayEnable = 'autoPlayEnable',
      fullScreenMode = 'fullScreenMode',
      preferCodecs = 'preferCodecs',
      defaultToastOp = 'defaultToastOp',
      defaultPicQa = 'defaultPicQa',
      enableHA = 'enableHA',
      audioOutput = 'audioOutput',
      bufferSize = 'bufferSize',
      bufferSec = 'bufferSec',
      hardwareDecoding = 'hardwareDecoding',
      videoSync = 'videoSync',
      autosync = 'autosync',
      p1080 = 'p1080',
      enableAutoEnter = 'enableAutoEnter',
      enableAutoExit = 'enableAutoExit',
      enableOnlineTotal = 'enableOnlineTotal',
      superChatType = 'superChatType',
      fullScreenSCWidth = 'fullScreenSCWidth',
      keyboardControl = 'keyboardControl',
      pauseOnMinimize = 'pauseOnMinimize',
      pgcSkipType = 'pgcSkipType',
      audioPlayMode = 'audioPlayMode',
      showBatteryLevel = 'showBatteryLevel',
      playerVolume = 'playerVolume',
      maxVolume = 'maxVolume';

  static const String enableVerticalExpand = 'enableVerticalExpand',
      feedBackEnable = 'feedBackEnable',
      enableLongShowControl = 'enableLongShowControl',
      horizontalScreen = 'horizontalScreen',
      CDNService = 'CDNService',
      disableAudioCDN = 'disableAudioCDN',
      autoPiP = 'autoPiP',
      enableAutoLongPressSpeed = 'enableAutoLongPressSpeed',
      useRelativeSlide = 'useRelativeSlide',
      sliderDuration = 'sliderOffset',
      enableQuickDouble = 'enableQuickDouble',
      fullScreenGestureReverse = 'fullScreenGestureReverse',
      enableBackgroundPlay = 'enableBackgroundPlay',
      continuePlayInBackground = 'continuePlayInBackground',
      appRcmd = 'appRcmd',
      enableSaveLastData = 'enableSaveLastData',
      minDurationForRcmd = 'minDurationForRcmd',
      minPlayForRcmd = 'minPlayForRcmd',
      minLikeRatioForRecommend = 'minLikeRatioForRecommend',
      exemptFilterForFollowed = 'exemptFilterForFollowed',
      banWordForRecommend = 'banWordForRecommend',
      applyFilterToRelatedVideos = 'applyFilterToRelatedVideos',
      autoUpdate = 'autoUpdate',
      maxCacheSize = 'maxCacheSize',
      defaultShowComment = 'defaultShowComment',
      replySortType = 'replySortType',
      defaultDynamicType = 'defaultDynamicType',
      showDynInteraction = 'showDynInteraction',
      enableHotKey = 'enableHotKey',
      enableSearchRcmd = 'enableSearchRcmd',
      enableQuickFav = 'enableQuickFav',
      enableWordRe = 'enableWordRe',
      enableSearchWord = 'enableSearchWord',
      enableSystemProxy = 'enableSystemProxy',
      enableAi = 'enableAi',
      disableLikeMsg = 'disableLikeMsg',
      defaultHomePage = 'defaultHomePage',
      previewQuality = 'previewQuality',
      checkDynamic = 'checkDynamic',
      dynamicPeriod = 'dynamicPeriod',
      schemeVariant = 'schemeVariant',
      showViewPoints = 'showViewPoints',
      showRelatedVideo = 'showRelatedVideo',
      showVideoReply = 'showVideoReply',
      showBangumiReply = 'showBangumiReply',
      alwaysExpandIntroPanel = 'alwaysExapndIntroPanel',
      expandIntroPanelH = 'exapndIntroPanelH',
      horizontalSeasonPanel = 'horizontalSeasonPanel',
      horizontalMemberPage = 'horizontalMemberPage',
      replyLengthLimit = 'replyLengthLimit',
      showArgueMsg = 'showArgueMsg',
      reverseFromFirst = 'reverseFromFirst',
      badCertificateCallback = 'badCertificateCallback',
      continuePlayingPart = 'continuePlayingPart',
      cdnSpeedTest = 'cdnSpeedTest',
      horizontalPreview = 'horizontalPreview',
      banWordForReply = 'banWordForReply',
      banWordForZone = 'banWordForZone',
      savedRcmdTip = 'savedRcmdTip',
      openInBrowser = 'openInBrowser',
      refreshDragPercentage = 'refreshDragPercentage',
      refreshDisplacement = 'refreshDisplacement',
      showHotRcmd = 'showHotRcmd',
      audioNormalization = 'audioNormalization',
      fallbackNormalization = 'fallbackNormalization',
      superResolutionType = 'superResolutionType',
      preInitPlayer = 'preInitPlayer',
      mainTabBarView = 'mainTabBarView',
      searchSuggestion = 'searchSuggestion',
      showDecorate = 'showDynDecorate',
      showMedal = 'showMedal',
      enableLivePhoto = 'enableLivePhoto',
      showSeekPreview = 'showSeekPreview',
      showDmChart = 'showDmChart',
      enableCommAntifraud = 'enableCommAntifraud',
      biliSendCommAntifraud = 'biliSendCommAntifraud',
      enableCreateDynAntifraud = 'enableCreateDynAntifraud',
      coinWithLike = 'coinWithLike',
      isPureBlackTheme = 'isPureBlackTheme',
      antiGoodsDyn = 'antiGoodsDyn',
      antiGoodsReply = 'antiGoodsReply',
      expandDynLivePanel = 'expandDynLivePanel',
      springDescription = 'springDescription',
      enableHttp2 = 'enableHttp2',
      slideDismissReplyPage = 'slideDismissReplyPage',
      showFSActionItem = 'showFSActionItem',
      enableShrinkVideoSize = 'enableShrinkVideoSize',
      showDynActionBar = 'showDynActionBar',
      darkVideoPage = 'darkVideoPage',
      enableSlideVolumeBrightness = 'enableSlideVolumeBrightness',
      enableSlideFS = 'enableSlideFS',
      retryCount = 'retryCount',
      retryDelay = 'retryDelay',
      liveQuality = 'liveQuality',
      liveQualityCellular = 'liveQualityCellular',
      appFontWeight = 'appFontWeight',
      fastForBackwardDuration = 'fastForBackwardDuration',
      recordSearchHistory = 'recordSearchHistory',
      showPgcTimeline = 'showPgcTimeline',
      pageTransition = 'pageTransition',
      optTabletNav = 'optTabletNav',
      banWordForDyn = 'banWordForDyn',
      enableLog = 'enableLog',
      memberTab = 'memberTab',
      dynamicDetailRatio = 'dynamicDetailRatio',
      directExitOnBack = 'directExitOnBack',
      quickFavId = 'quickFavId',
      showFsScreenshotBtn = 'showFsScreenshotBtn',
      showFsLockBtn = 'showFsLockBtn',
      silentDownImg = 'silentDownImg',
      showMemberShop = 'showMemberShop',
      enablePlayAll = 'enablePlayAll',
      enableTapDm = 'enableTapDm',
      setSystemBrightness = 'setSystemBrightness',
      downloadPath = 'downloadPath',
      followOrderType = 'followOrderType',
      enableImgMenu = 'enableImgMenu',
      showDynDispute = 'showDynDispute',
      touchSlopH = 'touchSlopH',
      floatingNavBar = 'floatingNavBar',
      removeSafeArea = 'removeSafeArea',
      angleDegrees = 'angleDegrees',
      liveStream = 'liveStream';

  static const String minimizeOnExit = 'minimizeOnExit',
      windowSize = 'windowSize',
      windowPosition = 'windowPosition',
      isWindowMaximized = 'isWindowMaximized',
      showWindowTitleBar = 'showWindowTitleBar',
      desktopVolume = 'desktopVolume',
      showTrayIcon = 'showTrayIcon',
      uiScale = 'uiScale';

  static const String subtitlePreferenceV2 = 'subtitlePreferenceV2',
      enableDragSubtitle = 'enableDragSubtitle',
      subtitlePaddingH = 'subtitlePaddingH',
      subtitlePaddingB = 'subtitlePaddingB',
      subtitleBgOpacity = 'subtitleBgOpaticy',
      subtitleStrokeWidth = 'subtitleStrokeWidth',
      subtitleFontScale = 'subtitleFontScale',
      subtitleFontScaleFS = 'subtitleFontScaleFS',
      subtitleFontWeight = 'subtitleFontWeight';

  static const String webdavUri = 'webdavUri',
      webdavUsername = 'webdavUsername',
      webdavPassword = 'webdavPassword',
      webdavDirectory = 'webdavDirectory';

  // === OFFLINE-NOSTALGIA-MODE BEGIN ===
  static const String offlineModeEnabled = 'offlineModeEnabled',
      offlineServerHost = 'offlineServerHost',
      offlineServerPort = 'offlineServerPort';
  // === OFFLINE-NOSTALGIA-MODE END ===

  static const String enableSponsorBlock = 'enableSponsorBlock',
      blockSettings = 'blockSettings',
      blockLimit = 'blockLimit',
      blockColor = 'blockColor',
      blockUserID = 'blockUserID',
      blockToast = 'blockToast',
      blockServer = 'blockServer',
      blockTrack = 'blockTrack';

  static const String enableShowDanmaku = 'enableShowDanmaku',
      enableShowLiveDanmaku = 'enableShowLiveDanmaku',
      pipNoDanmaku = 'pipNoDanmaku',
      showVipDanmaku = 'showVipDanmaku',
      mergeDanmaku = 'mergeDanmaku',
      danmakuWeight = 'danmakuWeight',
      danmakuBlockType = 'danmakuBlockType',
      danmakuShowArea = 'danmakuShowArea',
      danmakuOpacity = 'danmakuOpacity',
      danmakuFontScale = 'danmakuFontScale',
      danmakuFontScaleFS = 'danmakuFontScaleFS',
      danmakuDuration = 'danmakuDuration',
      danmakuStaticDuration = 'danmakuStaticDuration',
      danmakuMassiveMode = 'danmakuMassiveMode',
      danmakuFixedV = 'danmakuFixedV',
      danmakuStatic2Scroll = 'danmakuStatic2Scroll',
      danmakuLineHeight = 'danmakuLineHeight',
      danmakuStrokeWidth = 'strokeWidth',
      danmakuFontWeight = 'fontWeight';

  static const String systemProxyHost = 'systemProxyHost',
      systemProxyPort = 'systemProxyPort';

  static const String themeMode = 'themeMode',
      defaultTextScale = 'textScale',
      dynamicColor = 'dynamicColor',
      customColor = 'customColor',
      displayMode = 'displayMode',
      smallCardWidth = 'smallCardWidth',
      recommendCardWidth = 'recommendCardWidth',
      dynamicsWaterfallFlow = 'dynamicsWaterfallFlow',
      upPanelPosition = 'upPanelPosition',
      dynamicsShowAllFollowedUp = 'dynamicsShowAllFollowedUp',
      useSideBar = 'useSideBar',
      enableMYBar = 'enableMYBar',
      hideTopBar = 'hideSearchBar',
      hideBottomBar = 'hideTabBar',
      barHideType = 'barHideType',
      tabBarSort = 'tabBarSort',
      dynamicBadgeMode = 'dynamicBadgeMode',
      msgBadgeMode = 'msgBadgeMode',
      msgUnReadTypeV2 = 'msgUnReadTypeV2',
      navBarSort = 'navBarSort',
      tempPlayerConf = 'tempPlayerConf',
      reduceLuxColor = 'reduceLuxColor',
      liveCdnUrl = 'liveCdnUrl',
      saveReply = 'saveReply';
}

abstract final class LocalCacheKey {
  static const String historyPause = 'historyPause',
      blackMids = 'blackMids',
      danmakuFilterRules = 'danmakuFilterRules',
      mixinKey = 'mixinKey',
      timeStamp = 'timeStamp',
      buvid = 'buvid';

  // === OFFLINE-NOSTALGIA-MODE BEGIN ===
  // 单机怀旧模式下"发弹幕/评论/点赞"只写本地，永不上传，key 前缀 offline 区分。
  static const String offlineLikedBvids = 'offlineLikedBvids',
      offlineLocalDanmaku = 'offlineLocalDanmaku',
      offlineLocalReplies = 'offlineLocalReplies',
      // 三连/关注：仿照 blackMids 的 Set-in-localCache 模式
      offlineCoinedBvids = 'offlineCoinedBvids',
      offlineFavoritedBvids = 'offlineFavoritedBvids',
      offlineFollowedMids = 'offlineFollowedMids',
      // 视频级"不感兴趣"硬排除: Map<bvid, {reason, at}>
      offlineDislikedVideos = 'offlineDislikedVideos',
      // 带时间戳的观看历史日志(watchProgress只存位置没有历史): List<{bvid,cid,at,progressMs,durationMs}>
      offlineWatchHistory = 'offlineWatchHistory';
  // === OFFLINE-NOSTALGIA-MODE END ===
}

abstract final class VideoBoxKey {
  static const String playRepeat = 'playRepeat',
      playSpeedDefault = 'playSpeedDefault',
      longPressSpeedDefault = 'longPressSpeedDefault',
      speedsList = 'speedsList',
      cacheVideoFit = 'cacheVideoFit';
}
